name: virtkick
image: ubuntu-14-04-x64
min_size: 4gb
config:
  #cloud-config
  users:
    - name: admin
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
  runcmd:
    - cd /home/admin/ && sudo -u admin -s -- sh -c 'git clone https://github.com/duaperak-id/virtkick-starter.git && cd virtkick-starter && ./virtkick-start -dim'
